name: PLM
version: 0.4 BETA prerelease
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: Restores messages.txt or reloads Advanced Messages
    usage: /<command> restore/reload