general:
  enabled: true
  usePermissions: false
  useEssentialsNickName: true
  useRandomMessageSelection: false
welcomeMessages:
  delayMS: 200
publicMessages:
  usePermissions: false
vanish:
  usefakejoinmessage: false
  usefakequitmessage: false
  replaceVNPfakemessages: false
