name: PLM
version: 0.7.0 pr
api-version: '1.15'
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket, Essentials]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: '"plm restore" restores messages.txt or "plm reload" reloads the messages'
    usage: /<command> <restore|reload>