name: PLM
version: 0.7.0 pr
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket, EssentialsX]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: '"plm restore" restores messages.txt or "plm reload" reloads the messages'
    usage: /<command> <restore|reload>