name: PLM
version: 0.5 BETA
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket, Herochat]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: Restores messages.txt or reloads Advanced Messages
    usage: /<command> restore/reload