name: PLM
version: 0.5.2 BETA prerelease
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket, Herochat, Essentials]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: Restores messages.txt or reloads Advanced Messages
    usage: /<command> restore/reload