name: PLM
version: 0.5.3 BETA prerelease
author: FantasticSkyThrow
softdepend: [Vault, GeoIPTools, VanishNoPacket, Herochat, Essentials]

main: com.gmail.fantasticskythrow.PLM

commands:
  plm:
    description: '"plm restore" restores messages.txt or "plm reload" reloads the messages'
    usage: /<command> <restore|reload>